### ISSUE TITLE
eosdappdevenv_nodeosd_1 exited with code 254

### ISSUE THREAD

**Issue by jebuscraisp** [eoscostarica/eos-dapp-dev-env#9]
Unable to remove exit code 254, despite removing or commenting --replay-blockchain --hard-replay-blockchain. 
![s](https://user-images.githubusercontent.com/23113643/46927351-18ce2b00-cff2-11e8-9f4a-a18f2862de40.jpg)

**Comment by jebuscraisp** [comment]
https://eosforum.org/t/eosdappdevenv-nodeosd-1-exited-with-code-254/1704

**Comment by gaboesquivel** [comment]
hi @jebuscraisp we're doing a big refactor, you can follow that up on the [fast-forward-env](https://github.com/eoscostarica/eos-dapp-dev-env/tree/fast-forward-env) branch. 

Also checkout https://github.com/eosio/eosio.cdt, that simplifies contract compilation.
